### ISSUE TITLE
GraphQL Not working in aspnet core 3.0 preview 7 Blazor Server Side application

### ISSUE THREAD

**Issue by chanan** [graphql-dotnet/server#246]
I tried to use GraphQL in a Blazor Side application in asp.net core 3.0 preview7 (Both released and latest preview of GraphQL Transport)

I also tried per https://stackoverflow.com/questions/47735133/asp-net-core-synchronous-operations-are-disallowed-call-writeasync-or-set-all to add to StartUp but it didnt help:

```
services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
```
The error is:

```
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.Deserialize[T](Stream s)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by joemcbride** [comment]
Related to

https://github.com/graphql-dotnet/graphql-dotnet/issues/1116
https://github.com/graphql-dotnet/graphql-dotnet/issues/1148

**Comment by chanan** [comment]
Yes. It’s the same as #1116

I should point out that the workaround did not work for me in preview7 Blazor server side project

**Comment by Eilon** [comment]
@chanan - please see my comment at https://github.com/graphql-dotnet/graphql-dotnet/issues/1116#issuecomment-517444189 in case you're running on IIS and not Kestrel. The workaround worked for me.

**Comment by chanan** [comment]
No, its not from IIS, its from Visual Studio (preview version) using asp.net core 3 preview 7.

**Comment by Eilon** [comment]
Visual Studio is the IDE, but the app runs either on Kestrel (ASP.NET Core built-in web server) or on IIS (or IIS Express, more typically).

**Comment by Eilon** [comment]
From the stack trace you showed, it's IIS:

```
...
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
...
```

So you should use the IIS workaround I showed.

**Comment by chanan** [comment]
@Eilon you are correct, that fixed it. Thanks! (Closing this even though really this is just a workaround, but since there is already another open one to fix the async issue, you guys dont need this one as well).
