### ISSUE TITLE
System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[GraphQlVanilla.GraphQL.UserSchema]'.

### ISSUE THREAD

**Issue by NoamWe** [graphql-dotnet/server#354]
Hi,
Let me start by saying that I have read  the README.md and followed the example
This is the packaged in the project.  I am using netcoreapp3.1.
```
    <ItemGroup>
      <PackageReference Include="GraphQL" Version="3.0.0-preview-1490" />
      <PackageReference Include="GraphQL-Parser" Version="5.1.0" />
      <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0046" />
      <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="3.5.0-alpha0046" />
      <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0046" />
      <PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1490" />
      <PackageReference Include="MongoDB.Driver" Version="2.10.2" />
    </ItemGroup>
```
In my Schema I inject IServiceProvider since IDependencyResolver does not exist.
```
    public class UserSchema : Schema
    {
        public UserSchema(IServiceProvider resolver): base(resolver)
        {
            Query = resolver.GetRequiredService<UserQuery>();
        }
    }
```
This is my startup
```
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<UserSchema>();
            services.AddGraphQL(o => { o.ExposeExceptions = true; })
                .AddGraphTypes(ServiceLifetime.Scoped);
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseGraphQL<UserSchema>();
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());
        }
    }
```
When installing package 'GraphQL.Server.Transports.AspNetCore.SystemTextJson'
I saw this in the logs
```
info : Adding PackageReference for package 'GraphQL.Server.Transports.AspNetCore.SystemTextJson' into project '/home/noamwe/RiderProjects/GraphQlVanilla/GraphQlVanilla/GraphQlVanilla.csproj'.
info : Restoring packages for /home/noamwe/RiderProjects/GraphQlVanilla/GraphQlVanilla/GraphQlVanilla.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/graphql.server.transports.aspnetcore.systemtextjson/index.json
error: Unable to find a stable package GraphQL.Server.Transports.AspNetCore.SystemTextJson with version (>= 0.0.0)
error:   - Found 1 version(s) in nuget.org [ Nearest version: 3.5.0-alpha0046 ]
error: Package 'GraphQL.Server.Transports.AspNetCore.SystemTextJson' is incompatible with 'all' frameworks in project '/home/noamwe/RiderProjects/GraphQlVanilla/GraphQlVanilla/GraphQlVanilla.csproj'.
```
When running the project this is the error I get:
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[GraphQlVanilla.GraphQL.UserSchema]'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1[GraphQlVanilla.GraphQL.UserSchema]'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at GraphQlVanilla.Program.Main(String[] args) in /home/noamwe/RiderProjects/GraphQlVanilla/GraphQlVanilla/Program.cs:line 16
```

I would be most thankful for your assistance.

**Comment by sungam3r** [comment]
>  Package 'GraphQL.Server.Transports.AspNetCore.SystemTextJson' is incompatible with 'all' frameworks in project 

https://www.nuget.org/packages/GraphQL.Server.Transports.AspNetCore.SystemTextJson/3.5.0-alpha0046
![изображение](https://user-images.githubusercontent.com/21261007/78561442-6959c980-7820-11ea-9dc9-668737da6942.png)

> Let me start by saying that I have read the README.md and followed the example

https://github.com/graphql-dotnet/server#configure
![изображение](https://user-images.githubusercontent.com/21261007/78561534-91492d00-7820-11ea-9358-b26b3d30df1d.png)

**Comment by NoamWe** [comment]
Thanks for the reply, I managed to make it work.
