### ISSUE TITLE
TaskCanceledException when shutting down a server with subscriptions

### ISSUE THREAD

**Issue by Dravere** [graphql-dotnet/server#365]
I'm using GraphQL.Server.Transports.WebSockets version 3.4.0. When a subscription is initiated by a browser and thus a web socket connection is opened and kept open and I want to shutdown the server I get a TaskCanceledException on the server. Is there a possibility to have a proper shutdown?

Steps to reproduce:
1. Start server with subscription via web sockets
2. Subscribe from a GraphQL client (do not close that client, for example keep the browser tab open)
3. Stop the web host (server)

**Exception Log**:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM09DBNBBF82", Request id "0HM09DBNBBF82:00000001": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (One or more errors occurred. (The request was aborted)) ---> System.AggregateException: One or more errors occurred. (The request was aborted) ---> System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.StartTimingReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at GraphQL.Server.Transports.WebSockets.WebSocketReaderPipeline.ReadMessageAsync(ITargetBlock`1 target)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GraphQL.Server.Transports.Subscriptions.Abstractions.SubscriptionServer.OnConnect()
   at GraphQL.Server.Transports.WebSockets.WebSocketConnection.Connect()
   at GraphQL.Server.Transports.WebSockets.GraphQLWebSocketsMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (The request was aborted) ---> System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.StartTimingReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at GraphQL.Server.Transports.WebSockets.WebSocketReaderPipeline.ReadMessageAsync(ITargetBlock`1 target)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.StartTimingReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at GraphQL.Server.Transports.WebSockets.WebSocketReaderPipeline.ReadMessageAsync(ITargetBlock`1 target)<---
<---
```

**Comment by Dravere** [comment]
I've investigated this a bit further also to try to find a workaround. It seems the default implementation doesn't listen to the server lifetime callbacks at all. Thus it blocks on reading from the web socket reader pipeline until the server forcefully terminates/cancels it. I found a rather easy workaround to fix this. Not sure what the proper solution would be.

I've added my own `WebSocketConnectionFactory`. It is mostly the exact same code but I added a listener to the `IApplicationLifetime.ApplicationStopping` cancellation token (note: starting with Asp.Net Core 3, it would be `IHostApplicationLifetime`). The constructor gets the `IApplicationLifetime` object via DI.

```csharp
public class FixedWebSocketConnectionFactory<TSchema>
    : IWebSocketConnectionFactory<TSchema>
    where TSchema : ISchema
{
    private readonly ILogger _logger;
    private readonly ILoggerFactory _loggerFactory;
    private readonly IGraphQLExecuter<TSchema> _executer;
    private readonly IEnumerable<IOperationMessageListener> _messageListeners;
    private readonly IDocumentWriter _documentWriter;
    private readonly IApplicationLifetime _applicationLifetime;

    public FixedWebSocketConnectionFactory(
        ILogger<WebSocketConnectionFactory<TSchema>> logger,
        ILoggerFactory loggerFactory,
        IGraphQLExecuter<TSchema> executer,
        IEnumerable<IOperationMessageListener> messageListeners,
        IDocumentWriter documentWriter,
        IApplicationLifetime applicationLifetime)
    {
        this._logger = (ILogger) logger;
        this._loggerFactory = loggerFactory;
        this._executer = executer;
        this._messageListeners = messageListeners;
        this._documentWriter = documentWriter;
        this._applicationLifetime = applicationLifetime;
    }

    public WebSocketConnection CreateConnection(
        WebSocket socket,
        string connectionId)
    {
        this._logger.LogDebug("Creating server for connection {connectionId}", (object) connectionId);
        var transport = new WebSocketTransport(socket, this._documentWriter);
        var server = new SubscriptionServer(
            transport,
            new SubscriptionManager(this._executer, this._loggerFactory),
            this._messageListeners,
            this._loggerFactory.CreateLogger<SubscriptionServer>());

        // Terminate the server if the application is stopping
        var registration = this._applicationLifetime.ApplicationStopping.Register(() => server.Terminate());

        // Clean-up the listener if the web socket connection closed
        Task.Run(
            async () => {
                await transport.Reader.Completion;
                registration.Dispose();
            });
        
        return new WebSocketConnection(transport, server);
    }
}
```

Obviously the `FixedWebSocketConnectionFactory` class needs to be registered properly in the DI container.

```csharp
services.AddGraphQL().AddWebSockets();
services.AddTransient(typeof(IWebSocketConnectionFactory<>), typeof(FixedWebSocketConnectionFactory<>));
```

This seems to have fixed my problem. I hope it helps anyone finding this issue. And perhaps it can help fixing the core issue?

**Comment by sungam3r** [comment]
Thanks @Dravere , I will try you suggestions when I have time.

**Comment by Dravere** [comment]
After upgrading to GaphQL.Server 4.0.1 I retested this issue. It works much better in this version. There is no wait time during shutdown and it exits immediately. There is only a small nitpick left. There is still an uncaught `System.OperationCanceledException` left in the logs. But at least it cancels the operation properly while shutting down.

Full error with stack trace:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM3L0GMAU2D3", Request id "0HM3L0GMAU2D3:00000001": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (One or more errors occurred. (The read was canceled))
 ---> System.AggregateException: One or more errors occurred. (The read was canceled)
 ---> System.OperationCanceledException: The read was canceled
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at GraphQL.Server.Transports.WebSockets.WebSocketReaderPipeline.ReadMessageAsync(ITargetBlock`1 target)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GraphQL.Server.Transports.Subscriptions.Abstractions.SubscriptionServer.OnConnect()
   at GraphQL.Server.Transports.WebSockets.WebSocketConnection.Connect()
   at GraphQL.Server.Transports.WebSockets.GraphQLWebSocketsMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Shane32** [comment]
In GraphQL.NET Server v7, there is built-in support for `IApplicationLifetime.ApplicationStopping` and all shutdown should execute cleanly, with any anticipated exceptions being handled internally.  Please re-open if there are any continuing issues in v7.
