### ISSUE TITLE
Problem on last versions with NameConverter and SchemaFilter

### ISSUE THREAD

**Issue by MrPhelko** [graphql-dotnet/server#520]
In graphql-dotnet@4.0.1 
ExecutionOptions dont have NameConverter and SchemaFilter
im use net 5.0.2
```
System.MissingMethodException: Method not found: 'Void GraphQL.ExecutionOptions.set_NameConverter(GraphQL.Conversion.INameConverter)'.
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.GetOptions(String operationName, String query, Inputs variables, IDictionary`2 context, IServiceProvider requestServices, CancellationToken cancellationToken)
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.ExecuteAsync(String operationName, String query, Inputs variables, IDictionary`2 context, IServiceProvider requestServices, CancellationToken cancellationToken) in /_/src/Core/Internal/DefaultGraphQLExecuter.cs:line 45
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 144
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

also 

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<GraphQL.ErrorLocation> GraphQL.ExecutionError.get_Locations()'.
   at GraphQL.SystemTextJson.ExecutionResultJsonConverter.WriteErrors(Utf8JsonWriter writer, ExecutionErrors errors, IErrorInfoProvider errorInfoProvider, JsonSerializerOptions options)
   at GraphQL.SystemTextJson.ExecutionResultJsonConverter.Write(Utf8JsonWriter writer, ExecutionResult value, JsonSerializerOptions options) in /_/src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs:line 25
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 148
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sungam3r** [comment]
Current server packages are incompatible with GraphQL.NET v4.* , please wait a bit for release. The work is under the progress in the `develop` branch. See #477 .

**Comment by christianrondeau** [comment]
Is SchemaFilter still something you plan on implementing in the 5.x branch?

**Comment by sungam3r** [comment]
@christianrondeau Probably yes. I have a long break from OSS this year and I don't remember ) Feel free to open/reopen if you have suggestions.

**Comment by Shane32** [comment]
These properties were moved to the schema, correct?  I can't remember for sure, but I think they would be set in the schema constructor, not in the server project at all.

**Comment by sungam3r** [comment]
Yes, you are right.
