### ISSUE TITLE
Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime after upgrading to version 4

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/server#541]
Our application was working fine, I have updated to the latest version of all GQL dependencies in our net5.0 web app and the application fails to start with the below error.

### Expected result

Application should start up.

### Actual result

Exception thrown at runtime when trying to start up after upgrading all GQL dependencies to latest version:

Startup.cs - ConfigureServices
```
services.AddGraphQL((options, provider) =>
                {
                    var logger = provider.GetRequiredService<ILogger<Startup>>();
                    options.UnhandledExceptionDelegate = ctx =>
                        logger.LogError("{Error} occured", ctx.OriginalException.Message);
                    options.EnableMetrics = false;
                }).AddGraphTypes(ServiceLifetime.Scoped)
                .AddDataLoader()
                .AddWebSockets()
                .AddSystemTextJson();
```

Startup.cs - Configure
```
//Graphql
app.UseGraphQLWebSockets<CoreSchema>("/graphql");
app.UseGraphQL<CoreSchema>();
app.UseGraphQLPlayground();

```
```
<PackageReference Include="GraphQL" Version="4.2.0" />
<PackageReference Include="GraphQL.SystemTextJson" Version="4.2.0" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="5.0.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="4.2.0" />
```
Exception: 
```

Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime: Transient ImplementationType: GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule': Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime: Transient ImplementationType: GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule': Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MyProject.Program.Main(String[] args) in work/MyProject/GraphQL/Program.cs:line 13
```

**Comment by sungam3r** [comment]
`AuthorizationValidationRule` is from server project and it indeed depends from `IClaimsPrincipalAccessor`:
```csharp
 public AuthorizationValidationRule(IAuthorizationService authorizationService, IClaimsPrincipalAccessor claimsPrincipalAccessor)
```

Server project provides this method to add authorization into DI:
```csharp
 public static IGraphQLBuilder AddGraphQLAuthorization(this IGraphQLBuilder builder, Action<AuthorizationOptions> options)
        {
            builder.Services.TryAddTransient<IClaimsPrincipalAccessor, DefaultClaimsPrincipalAccessor>(); <---- LOOK HERE
            builder.Services
                .AddHttpContextAccessor()
                .AddTransient<IValidationRule, AuthorizationValidationRule>()
                .AddAuthorizationCore(options);

            return builder;
        }
```


Your startup only calls `AddGraphQL`. How do you configure authorization ?

**Comment by sungam3r** [comment]
>  The docs for moving from 3.X to 4.X said no calling code changes were needed re:authorization


Because thit is the docs for GraphQL.NET which does not contain authorization implementation but just a couple of extension methods to append string policies to fields and types. Authorization is from server project.

**Comment by markmcgookin** [comment]
> Your startup only calls `AddGraphQL`. How do you configure authorization ?

I had been handling it manually like a 'normal' dotnet web api... i.e.

```
services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    var authServer = Configuration.GetValue<string>("AuthorityServer");
                    options.Authority = authServer ?? "https://localhost:5005";
                    options.RequireHttpsMetadata = false;
                    options.ApiName = "my.api";
                    options.EnableCaching = true;
                    options.CacheDuration = TimeSpan.FromMinutes(10); // that's the default
                });

            services.AddAuthorization(options =>
                options.AddPolicy("AdminOnly",
                    policy => policy.RequireClaim("role", new List<string>() { "useradmin" })
                ));
```

**Comment by sungam3r** [comment]
So, how do you setup `AuthorizationValidationRule` in your DI then ?

**Comment by markmcgookin** [comment]
> So, how do you setup `AuthorizationValidationRule` in your DI then ?

Apologies, I forgot to answer this. Including the method you mentioned fixed the issue.

In the past I just had .AuthorizeWith(...) after each query and it worked abs applied the policy. I'll close this off as including that has made the error go away.

**Comment by MarkRogersEx** [comment]
I ran into the same error and had to add `AddGraphQLAuthorization` which fixed the issue.  While it all makes sense in the end, anyone who doesn't find this post is going to have to some experimentation to figure out what went wrong after upgrading.
