### ISSUE TITLE
System.InvalidOperationException: Cannot resolve 'Query' from root provider because it requires scoped service 'Context'.

### ISSUE THREAD

**Issue by basvandriel** [graphql-dotnet/server#696]
When having a scoped `DbContext` and setting up the GraphQL server like this;
```
var builder = GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(services);
builder.AddServer(true);
builder.AddSchema<Schema>();
builder.AddSystemTextJson();
builder.AddGraphTypes(typeof(Schema).Assembly);
```

I receive the following error;

```
System.InvalidOperationException: Cannot resolve 'Query' from root provider because it requires scoped service 'Context'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Infrastructure.Schema..ctor(IServiceProvider provider) in /home/bas/apps/lukas/src/Infrastructure/Schema.cs:line 11
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 160
   at Infrastructure.Identity.IdentityMiddleware.InvokeAsync(HttpContext context, Context appContext) in /home/bas/apps/lukas/src/Infrastructure/Identity/IdentityMiddleware.cs:line 39
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Query.cs

```
public class Query : ObjectGraphType<object>
{
    public Query(Context context)
    {
       ...
    }
}
```

**Comment by sungam3r** [comment]
Right. You added Query as singleton. Your Context is scoped. This is a well-known lifetime mismatch.

**Comment by sungam3r** [comment]
https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by basvandriel** [comment]
Can I still configure my schema like this?

```
public class Schema : GraphQL.Types.Schema
{
    public Schema(IServiceProvider provider) : base(provider)
    {
        Query = provider.GetRequiredService<Query>();
        Mutation = provider.GetRequiredService<Mutation>();
    }
}
```

**Comment by Shane32** [comment]
Sure

**Comment by sungam3r** [comment]
It depends.
```c#
 public class SchemaT
    {
        public SchemaT(IServiceProvider provider)
        {
            G = provider.GetRequiredService<GraphT>();
        }

        public GraphT G { get; set; }
    }

    public class GraphT
    {

    }
    public class Program
    {
        public static int Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddSingleton<SchemaT>();
            services.AddScoped<GraphT>();
            var provider = services.BuildServiceProvider(/*validateScopes: true*/); // <--- try this
            var r = provider.GetService<SchemaT>();
       }
}
```

**Comment by Shane32** [comment]
Right; you still need to match service lifetimes.

The documentation link @sungam3r posted above has a whole section on service lifetimes for schemas, and lists different methods to pull scoped services from a singleton schema.

**Comment by basvandriel** [comment]
Right! Thanks guys. Looked over that. Is there some workaround for not using a "service locator" as described in the docs?

**Comment by sungam3r** [comment]
All workarounds (basically all the options we came up with) are mentioned in the provided link.

**Comment by Shane32** [comment]
How brave are you? You can use the Shane32.GraphQL.DI project and set up graphs just like asp.net controllers, with no need to figure out the graph type to assign to each field and full support of dependency injection for services - scoped or not - within a singleton schema. 

https://github.com/Shane32/GraphQL.DI

Doesn’t support GraphQL interfaces or unions natively but you can mix typical code-first GraphQL.NET code with the generated graph types.

**Comment by Shane32** [comment]
Otherwise like @sungam3r says, we wrote out everything we could in the official docs. Not much else to say.
