### ISSUE TITLE
GraphQL.Server.Transports.AspNetCore.NewtonsoftJson v5.2.0 breaking changes

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/server#697]
Hey, I have just upgraded `GraphQL.Server.Transports.AspNetCore.NewtonsoftJson` from v5.1.1 to v 5.2.0 and it seems to have breaking changes on `DateTime` handling. We have fields of type `AnyScalarGraphType` that resolves into property with clr type `object`. Previously when date time string was sent in variables dictionary it was automatically parsed as `DateTime`, now it's a `string`. 

Trying to set `deserializationSettings.DateParseHandling = DateParseHandling.DateTime;` yields `Unexpected token type: Date` error:

```
System.InvalidOperationException: Unexpected token type: Date
    at GraphQL.NewtonsoftJson.InputsConverter.ReadValue(JsonReader reader) in /_/src/GraphQL.NewtonsoftJson/InputsConverter.cs:line 59
   at GraphQL.NewtonsoftJson.InputsConverter.ReadDictionary(JsonReader reader) in /_/src/GraphQL.NewtonsoftJson/InputsConverter.cs:line 43
   at GraphQL.NewtonsoftJson.InputsConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/GraphQL.NewtonsoftJson/InputsConverter.cs:line 17
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at GraphQL.Server.Transports.AspNetCore.NewtonsoftJson.GraphQLRequestDeserializer.DeserializeFromJsonBodyAsync(HttpRequest httpRequest, CancellationToken cancellationToken) in /_/src/Transports.AspNetCore.NewtonsoftJson/GraphQLRequestDeserializer.cs:line 57
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 93
```

Also `IGraphQLBuilder` was marked as obsolete but I couldn't find alternative way to register `GraphQL`.

**Comment by sungam3r** [comment]
See #569 , particularly this file https://github.com/graphql-dotnet/server/pull/569/files#r619586768

What is format of your date string?

**Comment by gao-artur** [comment]
The format is `"yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"`

**Comment by gao-artur** [comment]
To make it work as before I had to set `deserializationSettings.DateParseHandling = DateParseHandling.DateTime;` and add `JsonToken.Date => reader.Value,` to [InputsConverter.ReadValue()](https://github.com/graphql-dotnet/graphql-dotnet/blob/42b83821cbf224848531723d9689df6a2ae30c7c/src/GraphQL.NewtonsoftJson/InputsConverter.cs#L49)

**Comment by sungam3r** [comment]
@Shane32 Bug detected?

**Comment by sungam3r** [comment]
Also see `JsonToken.Bytes`.

**Comment by Shane32** [comment]
Yes: the inputs converter for newtonsoft should support DateTime. 

the fact that the newtonsoft converter deserializes dates as strings should be a known change for v4 but I could be wrong. Pretty sure we didn’t do anything recent to change deserialization defaults. 

Perhaps the fact that the server project is using the newtonsoft ToInputs method (it wasn’t before) could be different than the last version.

**Comment by Shane32** [comment]
> Also `IGraphQLBuilder` was marked as obsolete but I couldn't find alternative way to register `GraphQL`.

You can use the obsolete methods during the 5.x lifetime and they will be fully supported.

The interface is being replaced by the `IGraphQLBuilder` interface within GraphQL.NET.  You will need to import the nuget package `GraphQL.MicrosoftDI`, and then you will have access to the new `.AddGraphQL()` extension method to be able to use the new configuration builder.

The next major version of GraphQL.Server will remove the old builder interface and methods.

**Comment by gao-artur** [comment]
I see. Thanks for explanation.

**Comment by sungam3r** [comment]
Fixed in https://github.com/graphql-dotnet/graphql-dotnet/pull/2832

**Comment by Shane32** [comment]
Closing as answered; please reopen if there are further issues
